version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      androidx:
        patterns: ["androidx.*"]
      media3:
        patterns: ["androidx.media3:*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
